{% if CELERY_MULTIQUEUE_ENABLED and CELERY_ENABLE_KEDA_AUTOSCALING %}
{% for service, variants in CELERY_WORKER_VARIANTS.items() %}
{% for variant, config in variants.items() %}
{% set deployment = service + "-" + "worker" + "-" + variant.replace("_", "-") %}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ deployment }}-scaledobject
spec:
  minReplicaCount: {{ config.get("min_replicas", 0) }}
  maxReplicaCount: {{ config.get("min_replicas", 30) }}
  scaleTargetRef:
    kind: Deployment
    name: {{ deployment }}
  triggers:
  - metadata:
      {% if REDIS_HOST == 'redis'%}
      address: redis.{{K8S_NAMESPACE}}:{{REDIS_PORT}}
      {% else %}
      address: {{REDIS_HOST}}:{{REDIS_PORT}}
      {% endif %}
      listLength: {{ config.get("list_length", 40)}}
      listName: edx.{{service}}.core.{{variant}}
    type: redis
{% endfor %}
{% endfor %}
{% endif %}